FW/unittests: use designated initialisers for everything
Required by C++20:
WeightedTestSelector_tests.cpp:48:31: error: either all initializer clauses should be designated or none of them should be

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>