Fix build with libc++: #include <vector> was missing
framework/test_knobs.cpp:136:30: error: implicit instantiation of
undefined template 'std::vector<std::string>'

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>