FW/Linux: fix build "undefined reference to `kvm_generic_init'"
Amends commit 8bc4d2a9ddca7c3b73b003cfbd74ea3ebacbdff9 (I think),
restoring what was on a1232678014fb880b315aedc386c5602ec968feb (more or
less).

```
/usr/bin/ld: /__w/opendcdiag/opendcdiag/builddir/../framework/sandstone.cpp:783:(.text+0x2074): undefined reference to `kvm_generic_init'
/usr/bin/ld: /__w/opendcdiag/opendcdiag/builddir/../framework/sandstone.cpp:784:(.text+0x2078): undefined reference to `kvm_generic_run'
/usr/bin/ld: /__w/opendcdiag/opendcdiag/builddir/../framework/sandstone.cpp:784:(.text+0x207c): undefined reference to `kvm_generic_run'
/usr/bin/ld: /__w/opendcdiag/opendcdiag/builddir/../framework/sandstone.cpp:785:(.text+0x2084): undefined reference to `kvm_generic_cleanup'
/usr/bin/ld: /__w/opendcdiag/opendcdiag/builddir/../framework/sandstone.cpp:785:(.text+0x2088): undefined reference to `kvm_generic_cleanup'
```

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>