FW/Random: suppress warning about aliasing mismatched functions
Amends commit 50d7faf2931d34160c1143ea78f8441c31fedc8c.

```
random.cpp:712:38: warning: ‘int rand()’ alias between functions of incompatible types ‘int()’ and ‘long int()’ [-Wattribute-alias=]
  712 | __attribute__((alias("random"))) int rand();
      |                                      ^~~~
```

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>