Unit Tests: fix build - missing #include
I don't know why it's suddenly started failing in the GitHub CI:
```
../framework/unit-tests/sandstone_data_tests.cpp:71:27: error: no member named 'setfill' in namespace 'std'
    s << std::hex << std::setfill('0') << std::setw(8) << u;
                     ~~~~~^
../framework/unit-tests/sandstone_data_tests.cpp:71:48: error: no member named 'setw' in namespace 'std'
    s << std::hex << std::setfill('0') << std::setw(8) << u;
                                          ~~~~~^
```

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>