FW/Opts: Fix build: `std::to_chars` is in <charconv>
Amends commit 0d18b2647c69a92d6bf64dd01ce8d9f0f859e57b.

```
../opendcdiag/framework/sandstone_opts.cpp:419:27: error: 'to_chars' is not a member of 'std'
```

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>