FW: add missing #include for std::stringstream
Found in one of our internal builds:
```
../opendcdiag/framework/sandstone_tests.cpp: In function 'std::vector<test_cfg_info> load_test_list(std::ifstream&, SandstoneTestSet*, bool, std::vector<std::__cxx11::basic_string<char> >&)':
../opendcdiag/framework/sandstone_tests.cpp:197:35: error: aggregate 'std::stringstream msg_strm' has incomplete type and cannot be defined
```

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>