FW: move `thread_count()` and `num_packages()` to the `extern "C"` block
So they can be accessed from C code too. Their declarations were visible
from C code, but topology.cpp emitted them with mangled, causing
confusing errors like:
```
test.c:2222:(.text+0x688): undefined reference to `num_packages'
othertest.c:82: more undefined references to `num_packages' follow
```

Amends commit f93cabd0487229e951c7cf269bc1c84962f6d6c4 (#817).

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>