FW/Meson: move the common tests from tests_base.a to framework.a
The files aren't moved, but they are logically part of the framework.
That is especially true for the `mce_test`, because the framework
directly refers to it:

```
ld: opendcdiag/framework/libframework.a.p/sandstone.cpp.o: in function `main':
../opendcdiag/framework/sandstone.cpp:2716:(.text.startup+0xf98): undefined reference to `mce_test'
```

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>