Selftests: Fix build: impossible constraint in asm
Some compilers didn't like this "+gv" constraint:
```
selftest.cpp:937:13: error: impossible constraint in 'asm'
  937 |             __asm__ ("" : "+gv" (a_variable));
      |             ^~~~~~~
```

But we don't need the "v" here because we know `a_variable` is an
integer, therefore can only be stored in a general purpose register and
"g" is slightly more general-purpose than "r":

```
‘g’
     Any register, memory or immediate integer operand is allowed,
     except for registers that are not general registers.
...
‘r’
     A register operand is allowed provided that it is in a general
     register.
```
https://gcc.gnu.org/onlinedocs/gcc/Simple-Constraints.html

Also add the `volatile` marker, otherwise the compiler eliminates
because we didn't use the result of the statement.

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>