FW: warn if --enable and --test-list-file are used together
The test list file uses tests listed in the --enable only, but usually
one would expect the other way around. That leads to surprises.

$ echo eigen_svd > /tmp/list
$ ./opendcdiag --test-list-file /tmp/list -e zlib
ERROR: Attempt to specify non-existent test id [zlib] in list file

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>