FW: Fix amx_common.h for GCC >= 12
Depending on the order in which you included the files, our macros would
cause the GCC headers to fail:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/13.1.1/include/amxtileintrin.h:54:20: error: macro "_tile_release" passed 1 arguments, but takes just 0
   54 | _tile_release (void)
      |                    ^
In file included from framework/selftest.cpp:23:
framework/amx_common.h:60: note: macro "_tile_release" defined here
   60 | #define _tile_release()                         \
      |
```

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>