FW: fix build with no-test-names and a built-in test list
The sandstone_test_lists.cpp file refers to the test variables by
name, which we broke in commit aba09c034226c0931f82486cb6833b63bd9746d3.

```
ld: opendcdiag/framework/libframework.a.p/meson-generated_.._sandstone_test_lists.cpp.o:(.data.rel.ro+0x2e70): undefined reference to `_test_eigen_svd_double'
ld: opendcdiag/framework/libframework.a.p/meson-generated_.._sandstone_test_lists.cpp.o:(.data.rel.ro+0x2c58): undefined reference to `_test_eigen_gemm_cdouble_dynamic_square'
ld: opendcdiag/framework/libframework.a.p/meson-generated_.._sandstone_test_lists.cpp.o:(.data.rel.ro+0x2c60): undefined reference to `_test_eigen_svd_cdouble'
ld: opendcdiag/framework/libframework.a.p/meson-generated_.._sandstone_test_lists.cpp.o:(.data.rel.ro+0x2c68): undefined reference to `_test_eigen_svd'
ld: opendcdiag/framework/libframework.a.p/meson-generated_.._sandstone_test_lists.cpp.o:(.data.rel.ro+0x2c70): undefined reference to `_test_zlib'
```

The variable names can be left behind, because they disappear when the
executable is stripped of debugging information.

This isn't tested in the GitHub Actions CI, so it wasn't caught.

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>